<a href="https://colab.research.google.com/github/farfalan/codeforcesProblemset/blob/main/Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:

import numpy as np

# Create a 5x5 matrix filled with zeros
matrix = np.zeros((5, 5))

# Set a single element to 1 (let's choose the center)
matrix[4, 4] = 1
#Element to find
element = 1

# Finding the index of the element
result = np.where(matrix == element)

# Converting the result to a list of tuples
indices = list(zip(result[0], result[1]))

print(f"The index of element {element} is: {indices}")
print(matrix)
Y= abs(3-(result[0]+1))+ abs(3-(result[1]+1))
print(Y)

The index of element 1 is: [(4, 4)]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]]
[4]
